/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0PFRO4HuKLC
 */
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import Link from "next/link"

export function Component() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="w-full max-w-[1440px] p-8 space-y-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
        <h1 className="text-3xl font-bold text-center dark:text-white">Web Developer Portfolio</h1>
        <p className="text-center text-gray-600 dark:text-gray-400">
          Hi, I'm a web frontend developer. I specialize in creating interactive and dynamic web applications.
        </p>
        <h2 className="text-2xl font-bold text-center dark:text-white mt-8">Projects</h2>
        <div className="grid gap-6 sm:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg font-semibold dark:text-white">Project 1</CardTitle>
            </CardHeader>
            <CardContent>
              <img
                alt="Project 1"
                className="aspect-[5/3] object-cover w-full"
                height={300}
                src="/placeholder.svg"
                width={500}
              />
              <p className="mt-4 text-gray-600 dark:text-gray-400">A brief description of the project goes here.</p>
            </CardContent>
            <CardFooter className="flex justify-end">
              <Link className="text-blue-500 hover:underline dark:text-blue-400" href="#">
                View Details
              </Link>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle className="text-lg font-semibold dark:text-white">Project 2</CardTitle>
            </CardHeader>
            <CardContent>
              <img
                alt="Project 2"
                className="aspect-[5/3] object-cover w-full"
                height={300}
                src="/placeholder.svg"
                width={500}
              />
              <p className="mt-4 text-gray-600 dark:text-gray-400">A brief description of the project goes here.</p>
            </CardContent>
            <CardFooter className="flex justify-end">
              <Link className="text-blue-500 hover:underline dark:text-blue-400" href="#">
                View Details
              </Link>
            </CardFooter>
          </Card>
        </div>
        <div className="flex justify-center">
          <Link className="text-blue-500 hover:underline dark:text-blue-400" href="#">
            View More Projects
          </Link>
        </div>
      </div>
    </div>
  )
}
